### query
POST https://<mTLS_ENDPOINT_DNS_GOES_HERE>/search/
Content-Type: application/json

{
  "yql": "select * from product where Description contains \"premium cotton\" limit 5",
  "presentation.summary": "short"
}

### group by color
POST https://<mTLS_ENDPOINT_DNS_GOES_HERE>/search/
Content-Type: application/json

{
  "yql": "select * from product where true | all(group(PrimaryColor) each(output(count())))"
}